# Generated by Django 5.0.6 on 2024-06-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchFilterFunctions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
